// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// stacf1
double stacf1(NumericMatrix x, int timelag);
RcppExport SEXP stcor_stacf1(SEXP xSEXP, SEXP timelagSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP );
        Rcpp::traits::input_parameter< int >::type timelag(timelagSEXP );
        double __result = stacf1(x, timelag);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// stacf2
double stacf2(NumericMatrix x, NumericMatrix y, int timelag);
RcppExport SEXP stcor_stacf2(SEXP xSEXP, SEXP ySEXP, SEXP timelagSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP );
        Rcpp::traits::input_parameter< NumericMatrix >::type y(ySEXP );
        Rcpp::traits::input_parameter< int >::type timelag(timelagSEXP );
        double __result = stacf2(x, y, timelag);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// stacovf1
double stacovf1(NumericMatrix x, int timelag);
RcppExport SEXP stcor_stacovf1(SEXP xSEXP, SEXP timelagSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP );
        Rcpp::traits::input_parameter< int >::type timelag(timelagSEXP );
        double __result = stacovf1(x, timelag);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// stacovf2
double stacovf2(NumericMatrix x, int timelag, NumericMatrix w1);
RcppExport SEXP stcor_stacovf2(SEXP xSEXP, SEXP timelagSEXP, SEXP w1SEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP );
        Rcpp::traits::input_parameter< int >::type timelag(timelagSEXP );
        Rcpp::traits::input_parameter< NumericMatrix >::type w1(w1SEXP );
        double __result = stacovf2(x, timelag, w1);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// stacovf3
double stacovf3(NumericMatrix x, int timelag, NumericMatrix w2);
RcppExport SEXP stcor_stacovf3(SEXP xSEXP, SEXP timelagSEXP, SEXP w2SEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP );
        Rcpp::traits::input_parameter< int >::type timelag(timelagSEXP );
        Rcpp::traits::input_parameter< NumericMatrix >::type w2(w2SEXP );
        double __result = stacovf3(x, timelag, w2);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// stacovf4
double stacovf4(NumericMatrix x, int timelag, NumericMatrix w1, NumericMatrix w2);
RcppExport SEXP stcor_stacovf4(SEXP xSEXP, SEXP timelagSEXP, SEXP w1SEXP, SEXP w2SEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP );
        Rcpp::traits::input_parameter< int >::type timelag(timelagSEXP );
        Rcpp::traits::input_parameter< NumericMatrix >::type w1(w1SEXP );
        Rcpp::traits::input_parameter< NumericMatrix >::type w2(w2SEXP );
        double __result = stacovf4(x, timelag, w1, w2);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
